apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: php.movinite.id
  namespace: myphp-app
spec:
  secretName: php.movinite.id-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "php.movinite.id"
