apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: php.domain.com
  namespace: myphp-app
spec:
  secretName: php.domain.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "php.domain.com"