apiVersion: apps/v1
kind: Deployment
metadata:
  name: myphp-deployment
  namespace: myphp-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myphp-deployment
  template:
    metadata:
      labels:
        app: myphp-deployment
    spec:
      # imagePullSecrets:
      #   - name: gitlab-token
      containers:
        - name: myphp-deployment
          image: docker.io/randyproxz/php:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
      terminationGracePeriodSeconds: 0